repositories {
    mavenCentral()
    maven { url 'https://repo.dairy.foundation/releases/'}
    google() // Needed for androidx
}

dependencies {
    implementation libs.inspection
    implementation libs.blocks
    //noinspection Aligned16KB
    implementation libs.robotcore
    implementation libs.robotserver
    implementation libs.onbotjava
    implementation libs.hardware
    implementation libs.ftccommon
    implementation libs.vision
    implementation libs.appcompat

    implementation libs.core
    implementation libs.revhub
    implementation libs.tuning
    implementation libs.telemetry

    implementation libs.pedro
}